config/routes.rb
Rails.application.routes.draw do
  resources :links do
    resources :comments
  end
  resources :subreddits, only: [:new, :create, :index, :show]
  resources :users, only: [:new, :create, :show]

  root 'links#index'

     get 'signup' => 'users#new'
     get 'links/upvote/:id' => 'links#upvote', as: :upvote
     get 'links/upvote_button/:id' => 'links#upvote_button', as: :upvote_button
     get 'links/downvote_button/:id' => 'links#downvote_button', as: :downvote
     get 'login' => 'user_sessions#new'
     post 'login' => 'user_sessions#create'
     delete 'logout' => 'user_sessions#destroy', as: :logout

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link
  belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base

  belongs_to :user
  belongs_to :subreddit
  has_many :comments

  validates :title, presence: true
  validates :user, presence: true
  validates :link, presence: true, format: {:with => /\Ahttp:|https:\/\//}
  validates :thumbnail, presence: true
  validates :subreddit, presence: true

  default_scope { order(votes: :desc) }

end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base

  has_many :links

  validates :category, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :links
  has_many :comments

  validates :name, uniqueness: true, format: {:with => /\A[a-z0-9\-_]+\z/}
  validates :email, uniqueness: true, format: {:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}

  def to_param
    name
  end


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :link
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    if session[:name]
      @current_user ||= User.find_by_name(session[:name])
    end
    @current_user
  end

  def disallow_user
    if current_user
      flash[:danger] = "You are already logged in"
      redirect_to root_path
    end
  end

  def require_user
    unless current_user
      flash[:danger] = "You must log in to do that"
      redirect_to new_user_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, only: [:create]
  before_action :set_comment, only: [:show]

  def create
    @comment = current_user.comments.create!(
      link_id: params[:link_id],
      body: params[:comment][:body]
    )
    respond_to do |format|
      format.json {
        render json: @comment
      }
    end
  end

  def show
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :require_user, except: [:index, :show]
  before_action :set_link, only: [:show]

  def index
    @page_title = "Main Page"
    @links = Link.all.page(params[:page]).per(50)
  end

  def show
    @comment = Comment.new
  end

  def new
    @page_title = "New Post"
    @link = Link.new
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @page_title = "Edit Post"
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to root_path
  end

  def upvote
    @link = Link.find(params[:id])
    @link.increment!(:votes)
    redirect_to @link.link
  end

  def upvote_button
    @link = Link.find(params[:id])
    @link.increment!(:votes)
    render :downvote

  end

  def downvote_button
    @link = Link.find(params[:id])
    @link.decrement!(:votes)
    render :downvote
  end

  private

    def set_link
      @link = Link.find(params[:id])
    end

  def link_params
    params.require(:link).permit(:title, :link, :thumbnail, :subreddit_id, :summary)
  end

end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController

  before_action :require_user, except: [:index, :show]

  def index
    @page_title = "All Subreddits"
    @subreddits = Subreddit.all.order(category: :desc)
  end

  def show
    @subreddit = Subreddit.all.detect{|subreddit| subreddit.id == params[:id].to_i}
    @links = @subreddit.links.page(params[:page]).per(50)
  end

  def new
    @page_title = "Create New Subreddit"
    @subreddit = Subreddit.new
  end

  def create
    @subreddit = Subreddit.new(subreddit_params)
    if @subreddit.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def subreddit_params
    params.require(:subreddit).permit(:category, :description)
  end


end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  before_action :disallow_user, except: [:destroy]
  before_action :require_user, only: [:destroy]

  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user
      if @user.authenticate(params[:password])
        session[:name] = @user.name
        redirect_to root_path
      else
        render new_user_path
      end
    else
      render new_user_path
    end
  end

  def destroy
    session[:name] = nil
    redirect_to root_path
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, except: [:show, :new, :create]

  def show
    @users = User.find_by(name: params[:id])
    @links = @users.links.page(params[:page]).per(50)
  end

  def new
    @page_title = "Register New User"
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @page_title = "Edit User Profile"
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(post_params)
      redirect_to @user
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :bio, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_user

  def create
    @vote = current_user.votes.create!(
      value: params[:value] || 1,
      link_id: params[:link_id]
    )
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<div class="col-md-offset-1" id="comment_<%= comment.id %>">
  <p><%= comment.body %></p>
  <small>By: <%= comment.user.name %> on <%= link_to comment.created_at, link_comment_path(id: comment.id, link_id: comment.link.id) %></small>
</div>
<hr>

app/views/comments/show.html.erb
</br>
<%= render @comment.link %>
<%= render @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header class="row" id="header">
      <div class="col-md-3 col-md-offset-1">
        <%= image_tag "snoo.png", class: "img-responsive", id: "snoo"%>
        <h3 class="text-align-left" id="logo"><%= link_to "Reddit on Rails", root_path %></h3>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <h5 id="new_link"><%= link_to "Create Post", new_link_path %></h5>
        <h5 id="new_user"><%= link_to "New User", new_user_path %></h5>
        <h5 id="new_subreddit"><%= link_to "New Subreddit", new_subreddit_path %></h5>
      </div>
    </header>
    <main>
      <div class="row">
        <% if flash.any? %>
          <% flash.each do |key, message| %>
            <div class="alert alert-<%= key %>">
              <%= message %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row">
        <div class="col-md-8">

          <%= yield %>

        </div>
        <div class="col-md-3 col-md-offset-1">
          <div class = "form-control">
            <%= form_tag("/search", method: "get") do %>
              <%= label_tag(:f, "Search for:") %>
              <%= text_field_tag(:f) %>
              <%= submit_tag("Search") %>
            <% end %>
          </div>
          <br>
          <% if current_user %>
            <h4><%= "Welcome #{current_user.name}" %></h4>
            <%= button_to "Logout", logout_path, method: :delete %>
          <% else %>
             <div>
              <%= form_tag("/login", method: "post") do %>
                <fieldset class="form-group">
                  <%= label_tag(:name, "Username:") %>
                  <%= text_field_tag(:name) %>
                </fieldset>
                <fieldset class="form-group">
                  <%= label_tag(:password, "Password :") %>
                  <%= password_field_tag(:password) %>
                  <%= submit_tag("Login") %>
                <fieldset>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<% if link.errors.any? %>
  <ul>
    <% link.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="row">
    <div class="col-md-11 col-md-offset-1">
      <%= form_for link do |f| %>
        <fieldset class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, :class => "form-control", :placeholder => "Link Title" %>
        </fieldset>
        <fieldset class="form-group">
          <%= f.label :subreddit_id %>
          <%= f.collection_select :subreddit_id, Subreddit.order(:id),:id,:category, {include_blank: true}, {:class => "form-control"} %>
        </fieldset>
        <fieldset class="form-group">
          <%= f.label :thumbnail %>
          <%= f.text_field :thumbnail, :class => "form-control", :placeholder => "Thumbnail URL" %>
        </fieldset>
        <fieldset class="form-group">
          <%= f.label :link %>
          <%= f.text_field :link, :class => "form-control", :placeholder => "Post link URL here." %>
        </fieldset>
        <fieldset class="form-group">
          <%= f.label :summary %>
          <%= f.text_area :summary, :class => "form-control", :placeholder => "Optional short summary here." %>
        </fieldset>
          <%= f.submit :class => "btn btn-primary submit-button" %>
          <small class="text-muted">Please ensure all fields have been completed</small>
      <% end %>
    </div>
  </div>

app/views/links/_link.html.erb
<div class ="row" id="link_<%= link.id %>">
  <div class ="col-md-1 col-md-offset-1">
    <%= button_to upvote_button_path(id: link.id), :method => :get, remote: true do %>
        <span class = "btn btn-xs glyphicon glyphicon-arrow-up"></span>
    <% end %>
    <p class="votes"><%= link.votes %></p>
    <%= button_to downvote_path(id: link.id), :method => :get, remote: true do %>
        <span class="btn btn-xs glyphicon glyphicon-arrow-down"></span>
    <% end %>
  </div>
  <div class="col-md-2">
    <%= image_tag link.thumbnail, class: "img-rounded img-responsive link_icon" %>
  </div>
  <div class="col-md-7 row link_info">
    <div class="col-md-12">
      <p><%= link_to link.title, upvote_path(id: link.id) %> in <%= link_to link.subreddit.category, subreddit_path(id: link.subreddit.id) %></p>
    </div>
    <div class="col-md-12">
      <p><%= (truncate(link.summary, length: 250, separator: " ")) %></p>
    </div>
    <div class="col-md-12">
      <p>Created by: <%= link_to link.user.name, link.user %> on <%= link_to link.created_at, link  %></p>
    </div>
  </div>
</div>
<hr>

app/views/links/downvote.js.erb
$('#link_<%= @link.id %> .votes' ).text('<%= @link.votes %>')

app/views/links/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= paginate @links %>
  </div>
  <div class="col-md-2 col-md-offset-3 text-align-right">
    <%= link_to "List of Subreddits", subreddits_path %>
  </div>
</div>
  <%= render @links %>
<div class="col-md-offset-1">
  <%= paginate @links %>
</div>

app/views/links/new.html.erb
<h2>Create a New Post</h2>

<%= render partial: "form", locals: {link: @link} %>

app/views/links/show.html.erb
</br>
<div class ="row" id="link_<%= @link.id %>">
  <div class ="col-md-1 col-md-offset-1">
    <%= button_to upvote_button_path(id: @link.id), :method => :get, remote: true do %>
        <span class = "btn btn-xs glyphicon glyphicon-arrow-up"></span>
    <% end %>
    <p class="votes"><%= @link.votes %></p>
    <%= button_to downvote_path(id: @link.id), :method => :get, remote: true do %>
        <span class="btn btn-xs glyphicon glyphicon-arrow-down"></span>
    <% end %>
  </div>
  <div class="col-md-2">
    <%= image_tag @link.thumbnail, class: "img-rounded img-responsive link_icon" %>
  </div>
  <div class="col-md-7 row link_info">
    <div class="col-md-12">
      <p><%= link_to @link.title, upvote_path(id: @link.id) %> in <%= link_to @link.subreddit.category, subreddit_path(id: @link.subreddit.id) %></p>
    </div>
    <div class="col-md-12">
      <p><%= @link.summary %></p>
    </div>
    <div class="col-md-12">
      <p>Created by: <%= link_to @link.user.name, @link.user %> on <%= link_to @link.created_at, @link  %></p>
    </div>
  </div>
</div>
<hr>
</br>
<div class="row">
  <div class="col-md-8 col-md-offset-1">
    <%= form_for [@link, @comment] do |f| %>
      <fieldset class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, :class => "form-control", :placeholder => "What do you think?" %>
      </fieldset>
      <%= f.submit :class => "btn btn-primary submit-button" %>
    <% end %>
  </div>
</div>
<hr />
<div id="link_comments">
  <%= render @link.comments %>
</div>

app/views/subreddits/index.html.erb
<br>
<% @subreddits.each do |subreddit| %>
  <div class ="row">
    <div class="col-md-11 col-md-offset-1">
      <p><%= link_to subreddit.category, subreddit_path(id: subreddit.id) %> : <%= subreddit.description %></p>
    </div>
  </div>
<% end %>

app/views/subreddits/new.html.erb
<h2>Create New Subreddit</h2>

<% if @subreddit.errors.any? %>
  <ul>
    <% @subreddit.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<div class="row">
  <div class="col-md-11 col-md-offset-1">
    <%= form_for @subreddit do |f| %>
      <fieldset class="form-group">
        <%= f.label :category %>
        <%= f.text_field :category, :class => "form-control", :placeholder => "Subreddit Name" %>
      </fieldset>
      <fieldset class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, :class => "form-control", :placeholder => "Subreddit description." %>
      </fieldset>
      <%= f.submit :class => "btn btn-primary submit-button" %>
      <small class="text-muted">Please ensure all fields have been completed</small>
    <% end %>
  </div>
</div>

app/views/subreddits/show.html.erb
<div class="row">
  <h3 class="col-md-offset-1">Posts from <%= @subreddit.category %></h3>
</div>
<%= render @subreddit.links %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<div class="row">
  <div class="col-md-11 col-md-offset-1">
    <%= form_for @user do |f| %>
      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => "form-control", :placeholder => "Username" %>
      </fieldset>
      <fieldset class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, :class => "form-control", :placeholder => "Valid email address." %>
      </fieldset>
      <fieldset class="form-group">
        <%= f.label :bio %>
        <%= f.text_area :bio, :class => "form-control", :placeholder => "Optional Bio Information" %>
      </fieldset>  
      <fieldset class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, :class => "form-control", :placeholder => "Password" %>
      </fieldset>
      <fieldset class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "Confirm Password" %>
      </fieldset>
      <%= f.submit :class => "btn btn-primary submit-button" %>
      <small class="text-muted">Please ensure all fields have been completed</small>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Register New User</h2>

<%= render partial: "form", locals: {user: @user} %>

app/views/users/show.html.erb
<div class="row">
  <h3 class="col-md-offset-1"><%= @users.name %> posts</h3>
</div>
<div class="row">
  <p class="col-md-offset-1"><%= @users.bio %></p>
</div>

<%= render @users.links %>